name: dune
description: Stream music aesthetically.

publish_to: 'none'


version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  system_theme: ^2.3.1
  flutter_acrylic: ^1.1.2
  url_launcher: ^6.1.10
  file_picker: ^5.5.0
  fluent_ui: ^4.7.4
  http: ^1.0.0
  youtube_explode_dart: ^2.0.1
  loading_animation_widget: ^1.0.0+3
  audio_video_progress_bar: ^2.0.0
  window_manager: ^0.3.6
  flutter_staggered_animations: ^1.1.1
  extended_image: ^8.0.1
  flutter_riverpod: ^2.4.0
  shimmer_animation: ^2.1.0+1
  media_kit: ^1.1.7
  media_kit_libs_audio: ^1.0.1
  font_awesome_flutter: ^10.5.0
  easy_debounce: ^2.0.3
  riverpod_infinite_scroll: ^1.0.9
  go_router: ^11.0.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  logger: ^2.0.1
  get_it: ^7.6.4
  equatable:
    path: ./external/equatable-master
  collection: ^1.17.1
  path_provider:
  faker: ^2.1.0
  device_preview: ^1.1.0
  path: ^1.8.3
  flutter_taggy: ^0.1.2+3
  infinite_scroll_pagination: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  flutter_native_splash: ^2.1.6
  build_verify: ^3.1.0
  msix: ^3.15.0
  go_router_builder: ^2.2.3
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/fonts/
  fonts:
    - family: baloo2
      fonts:
        - asset: assets/fonts/Baloo2.ttf
    - family: bruno_ace
      fonts:
        - asset: assets/fonts/BrunoAceSC.ttf
    - family: work_sans
      fonts:
        - asset: assets/fonts/WorkSans-Light.ttf
        - asset: assets/fonts/WorkSans-Medium.ttf
        - asset: assets/fonts/WorkSans-Regular.ttf

msix_config:
  display_name: DUNE
  publisher_display_name: DoraGon
  identity_name: mouayad.dune-music
  msix_version: 1.0.0.0
  logo_path:
  capabilities: "internetClient"
  app_installer: #<-- app installer configuration
    publish_folder_path: ./assets/releases/
    hours_between_update_checks: 0
    automatic_background_task: true
    update_blocks_activation: true
    show_prompt: true
    force_update_from_any_version: false